apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
    testid: {{ .Values.testid }}
spec:
  type: "{{ .Values.serviceType }}"
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: frontend
